# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nikhil NAD Haksar
email: nhaksar@cs.uchicago.edu
description: > # this means to ignore newlines until "baseurl:"
  Applied microeconomics; competition economics; industrial organization.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nhaksar.github.io" # the base hostname & protocol for your site
twitter_username: NikhilHaksar
github_username:  nhaksar

# Build settings
markdown: kramdown
